GUIDELINES = {
"multiconer_scientist": {"en": ["A person who conducts scientific research, experiments, and investigations in fields such as physics, chemistry, biology, or astronomy. This includes both renowned scientists (e.g., Edward Jenner, Elon Musk) and fictional characters known for scientific pursuits (e.g., Spider-Man)."]},
"multiconer_artist": {"en": ["A person who creates or practices any form of art, including visual arts (e.g., painting, sculpture), performing arts (e.g., music, theater), or literary arts (e.g., writing). This category encompasses renowned artists across various disciplines (e.g., Bob Dylan, William Shakespeare) as well as fictional artistic characters."]},
"multiconer_athlete": {"en": ["An individual who actively participates in sports, athletic competitions, or physical activities at a professional or amateur level (e.g., Michael Jordan, Jeff Gordon). This category can also include fictional characters known for their athletic prowess or association with sports."]},
"multiconer_politician": {"en": ["A person involved in politics and government, including elected officials, political leaders, and individuals engaged in influencing public policy or decision-making (e.g., Margaret Thatcher, George Washington). This category may also include fictional political characters or figures."]},
"multiconer_cleric": {"en": ["A member of a religious clergy or ministry, such as a priest, minister, rabbi, or imam (e.g., John Calvin, Jonathan Swift). This category encompasses both real-world religious leaders and fictional characters associated with religious roles or organizations."]},
"multiconer_sports_manager": {"en": ["An individual responsible for managing, coaching, or overseeing the operations of a sports team or athletic organization (e.g., Jon Hoke, Mike Shanahan). This category includes both real-world sports managers and fictional characters in similar roles."]},
"multiconer_other_person": {"en": ["An individual who does not fit into any of the other defined categories for persons, such as historical figures, famous personalities, or fictional characters not associated with specific fields or professions (e.g., Edward Meyrick, Francis Walker)."]},
"multiconer_musical_group": {"en": ["A group of musicians or vocalists who perform music together, such as a band, choir, orchestra, or ensemble (e.g., The Beatles, Pink Floyd). This category includes both real-world musical groups and fictional or imaginary bands or ensembles."]},
"multiconer_public_corp": {"en": ["A company or corporation that is owned by the public and whose shares are traded on a stock exchange (e.g., Apple, Netflix). This category includes well-known public corporations from various industries and sectors."]},
"multiconer_private_corp": {"en": ["A company or corporation that is privately owned and not publicly traded on a stock exchange (e.g., Chanel, Bell Labs). This category encompasses private corporations, including both real-world companies and fictional or imaginary private entities."]},
"multiconer_aerospace_manufacturer": {"en": ["A company that specializes in the manufacturing and production of aircraft, spacecraft, or related aerospace products and components (e.g., Boeing, British Aerospace). This category includes both real-world aerospace manufacturers and fictional or imaginary companies in the same industry."]},
"multiconer_sports_group": {"en": ["A group or organization involved in sports activities, such as a professional or amateur sports team, league, or association (e.g., New York Jets, Boston Red Sox). This category includes both real-world sports groups and fictional or imaginary teams or leagues."]},
"multiconer_other_group": {"en": ["A group or organization that does not fit into any of the other defined categories for groups, such as non-profit organizations, government agencies, media outlets, or fictional groups (e.g., United States Census Bureau, Rotten Tomatoes, Republican Party)."]},
"multiconer_visual_work": {"en": ["A creative work or artistic production that is primarily visual in nature, such as a painting, sculpture, photograph, film, or television series (e.g., 'Doctor Who', 'Music Video'). This category includes both real-world visual works and fictional or imaginary visual productions."]},
"multiconer_musical_work": {"en": ["A musical composition or piece of music, such as a song, symphony, opera, or album (e.g., 'The Man I Love', 'Opera'). This category encompasses both real-world musical works and fictional or imaginary musical compositions."]},
"multiconer_written_work": {"en": ["A literary work or written piece, such as a book, novel, play, poem, or publication (e.g., 'National Register of Historic Places', 'The New York Times'). This category includes both real-world written works and fictional or imaginary literary productions."]},
"multiconer_art_work": {"en": ["A creative work or piece of art, such as a painting, sculpture, installation, or other artistic creation (e.g., 'The Threatened Swan', 'Installation Art'). This category encompasses both real-world artworks and fictional or imaginary artistic works."]},
"multiconer_software": {"en": ["A set of computer programs and associated data designed to perform specific tasks or operations, such as operating systems, applications, or web services (e.g., YouTube, Facebook, Twitter)."]},
"multiconer_facility": {"en": ["A building or complex designed for a particular purpose, such as a museum, hospital, school, or research facility (e.g., Metropolitan Museum of Art, British Museum). This category includes both real-world facilities and fictional or imaginary buildings or complexes."]},
"multiconer_human_settlement": {"en": ["A populated area where people live and work, such as a city, town, village, or country (e.g., New York City, United States, France). This category encompasses both real-world human settlements and fictional or imaginary locations."]},
"multiconer_station": {"en": ["A specific location or building designed for a particular purpose, such as a train station, bus station, airport, or space station (e.g., Malmö, Jammu Airport). This category includes both real-world stations and fictional or imaginary stations or facilities."]},
"multiconer_other_location": {"en": ["A location or place that does not fit into any of the other defined categories for locations, such as museums, landmarks, or fictional places (e.g., Songwriters Hall of Fame, National Museum of Racing and Hall of Fame)."]},
"multiconer_clothing": {"en": ["An item of garment or apparel worn to cover or protect the body, such as a shirt, pants, dress, or accessory (e.g., Trench Coat, Personal Protective Equipment). This category includes both real-world clothing items and fictional or imaginary garments or accessories."]},
"multiconer_vehicle": {"en": ["A means of transportation, such as a car, truck, airplane, spacecraft, or watercraft (e.g., Schooner, Sloop, U-Boat). This category encompasses both real-world vehicles and fictional or imaginary modes of transportation."]},
"multiconer_food": {"en": ["A solid substance that is typically eaten and provides nourishment or sustenance, such as fruits, vegetables, grains, or meat (e.g., Salt, Rice, Sugar). This category includes both real-world food items and fictional or imaginary edible substances."]},
"multiconer_drink": {"en": ["A liquid substance that is intended for consumption, such as water, juice, soda, or an alcoholic beverage (e.g., Coffee, Wine, Coca-Cola). This category includes both real-world drinks and fictional or imaginary beverages."]},
"multiconer_other_product": {"en": ["A product or manufactured item that does not fit into any of the other defined categories for products, such as consumer goods, equipment, or fictional products (e.g., PlayStation 3, Wheelchair, Ecotourism)."]},
"multiconer_medication_or_vaccine": {"en": ["A substance or preparation used in the treatment or prevention of disease, including drugs, medications, vaccines, and medical compounds (e.g., Ethanol, Analgesic, Calcium)."]},
"multiconer_medical_procedure": {"en": ["A specific process, treatment, or intervention used in the practice of medicine or healthcare, such as surgical procedures, diagnostic tests, or therapeutic interventions (e.g., Chemotherapy, Vaccination, Electrotherapy)."]},
"multiconer_anatomical_structure": {"en": ["A specific part or structure of the body, such as an organ, tissue, or body system (e.g., Petiole, Inflorescence, Flesh). This category includes both human and animal anatomical structures."]},
"multiconer_symptom": {"en": ["A physical or mental manifestation that is experienced as a consequence of a disease or medical condition (e.g., Pain, Anxiety, Inflammation). This category encompasses both common symptoms and specific symptoms associated with particular diseases or disorders (e.g., HIV/AIDS, Cystic Fibrosis)."]},
"multiconer_disease": {"en": ["A disorder or abnormal condition that affects the body or mind and causes specific symptoms or impairments (e.g., Tuberculosis, Multiple Sclerosis, Schizophrenia). This category includes both well-known diseases and rare or obscure medical conditions."]},
}

EXAMPLES = {
    "multiconer_other_person_examples": {"en": ["edward meyrick", "stephan von breuning", "francis walker", "george hampson", "per olof christopher aurivillius"]},
"multiconer_visual_work_examples": {"en": ["music video", "doctor who", "american idol", "lost film", "lost"]},
"multiconer_other_group_examples": {"en": ["united states census bureau", "rotten tomatoes", "bbc", "republican", "abc"]},
"multiconer_artist_examples": {"en": ["bob dylan", "paul mccartney", "duke ellington", "william shakespeare", "richard rodgers"]},
"multiconer_human_settlement_examples": {"en": ["new york city", "united states", "france", "paris", "japan"]},
"multiconer_written_work_examples": {"en": ["national register of historic places", "the new york times", "first described", "the washington post", "rolling stone"]},
"multiconer_software_examples": {"en": ["youtube", "facebook", "twitter", "itunes", "android"]},
"multiconer_politician_examples": {"en": ["margaret thatcher", "napoleon", "lord walsingham", "victor hugo", "george washington"]},
"multiconer_athlete_examples": {"en": ["michael jordan", "kyle larson", "batman", "bob hope", "jeff gordon"]},
"multiconer_musical_work_examples": {"en": ["opera", "studio album", "movements", "the man i love", "down bad"]},
"multiconer_facility_examples": {"en": ["metropolitan museum of art", "white house", "british museum", "national gallery of canada", "boarding school"]},
"multiconer_scientist_examples": {"en": ["spider-man", "richard garriott", "edward jenner", "john rennie", "elon musk"]},
"multiconer_cleric_examples": {"en": ["paulin martin", "jonathan swift", "eusebius", "john calvin", "little richard"]},
"multiconer_sports_group_examples": {"en": ["new york jets", "boston red sox", "detroit lions", "cleveland browns", "carolina panthers"]},
"multiconer_musical_group_examples": {"en": ["the beatles", "pink floyd", "led zeppelin", "pearl jam", "the beach boys"]},
"multiconer_sports_manager_examples": {"en": ["jon hoke", "mike shanahan", "dennis johnson", "edgar diddle", "mike bibby"]},
"multiconer_public_corp_examples": {"en": ["netflix", "oricon", "canadian pacific railway", "apple", "mcdonald 's"]},
"multiconer_other_product_examples": {"en": ["playstation 3", "pulpit", "ecotourism", "playstation", "wheelchair"]},
"multiconer_medical_procedure_examples": {"en": ["chemotherapy", "abortion", "vaccination", "electrotherapy", "urinalysis"]},
"multiconer_art_work_examples": {"en": ["installation art", "the threatened swan", "the banquet of the officers of the st george militia company in 1616", "matte painting", "hanging scroll"]},
"multiconer_food_examples": {"en": ["salt", "vinegar", "rice", "sugar", "honey"]},
"multiconer_station_examples": {"en": ["malmö", "bus station", "airports", "raf akrotiri", "jammu airport"]},
"multiconer_aerospace_manufacturer_examples": {"en": ["british aerospace", "boeing", "north american aviation", "de havilland", "cessna"]},
"multiconer_other_location_examples": {"en": ["songwriters hall of fame", "handrail", "national museum of racing and hall of fame", "reservoir", "museum"]},
"multiconer_private_corp_examples": {"en": ["chanel", "world championship wrestling", "bell labs", "elite model management", "the wire"]},
"multiconer_disease_examples": {"en": ["tuberculosis", "pneumonia", "multiple sclerosis", "schizophrenia", "smallpox"]},
"multiconer_vehicle_examples": {"en": ["schooner", "sloop", "ships", "u-boat", "galleys"]},
"multiconer_medication_or_vaccine_examples": {"en": ["ethanol", "iron", "analgesic", "calcium", "acetic acid"]},
"multiconer_symptom_examples": {"en": ["pain", "hiv/aids", "anxiety", "inflammation", "cystic fibrosis"]},
"multiconer_anatomical_structure_examples": {"en": ["petiole", "flowers", "inflorescence", "columella", "flesh"]},
"multiconer_drink_examples": {"en": ["coffee", "milk", "wine", "coca-cola", "beer"]},
"multiconer_clothing_examples": {"en": ["pilasters", "caps", "trench coat", "umbrella", "personal protective equipment"]}
}
